import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Snb from '@repo/ui/layouts/Snb';

const pretendard = localFont({
  src: '../../../../packages/tailwind-config/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={pretendard.className}>
        <div className='grid min-h-screen w-full grid-cols-[97px_1fr]'>
          <Snb />
          <main className='w-full'>{children}</main>
        </div>
      </body>
    </html>
  );
}
